"""LLM-based verbalizer.

For each activation we want a natural-language description. We:
  1. Find its k nearest-neighbour texts in activation space.
  2. Prompt a small instruction-tuned LM (the same SmolLM2 we extract
     activations from) to summarize what those neighbours share in a
     single short sentence.
  3. Use that sentence as the explanation.

This is the "natural language" form the paper asks for: the explanation
is a real sentence generated by an LM, and it is genuinely conditioned
on the activation (via its neighbourhood). Two activations whose
neighbours differ will get different sentences.

To keep generation cost bounded for N=2000 samples, we cache one
explanation per unique neighbourhood. By default the neighbourhood
identifier is the KMeans cluster the activation falls in, so we make
K=num_clusters generation calls instead of N.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
import torch
from tqdm import tqdm

from .model_utils import LoadedModel


SYSTEM_PROMPT = (
    "You are a research assistant labelling clusters of text. "
    "Given several example passages that share an underlying topic or style, "
    "write ONE short sentence (max 20 words) that captures what they have in common. "
    "The sentence must start with 'This activation is related to' and describe the shared content. "
    "Be specific. Avoid generic words like 'various', 'different', or 'text'. "
    "Do not list the examples. Do not add preamble. Output only the sentence."
)


def _build_prompt(tokenizer, example_texts: list[str]) -> str:
    bullets = "\n".join(f"- {t.strip()[:240]}" for t in example_texts)
    user_msg = (
        "Here are example passages from one cluster:\n\n"
        f"{bullets}\n\n"
        "Write one sentence that starts with 'This activation is related to' "
        "and describes what the passages share."
    )
    # Use the model's own chat template when available; fall back to a plain
    # instruction format for models without one.
    if getattr(tokenizer, "chat_template", None):
        msgs = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ]
        return tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True
        )
    return f"{SYSTEM_PROMPT}\n\n{user_msg}\n\nAnswer:"


@torch.no_grad()
def _generate_one(
    loaded: LoadedModel,
    prompt: str,
    max_new_tokens: int,
) -> str:
    enc = loaded.tokenizer(prompt, return_tensors="pt").to(loaded.device)
    out = loaded.model.generate(
        **enc,
        max_new_tokens=max_new_tokens,
        do_sample=False,             # deterministic for reproducibility
        temperature=1.0,
        top_p=1.0,
        pad_token_id=loaded.tokenizer.pad_token_id,
        eos_token_id=loaded.tokenizer.eos_token_id,
        repetition_penalty=1.1,
    )
    full = loaded.tokenizer.decode(out[0], skip_special_tokens=True)
    # Strip the prompt prefix to keep only the model's answer.
    answer = full[len(loaded.tokenizer.decode(enc["input_ids"][0], skip_special_tokens=True)) :]
    return _clean_answer(answer)


def _clean_answer(text: str) -> str:
    """Take the first non-empty line; trim leading bullets, asterisks, quotes."""
    text = text.strip()
    for line in text.split("\n"):
        line = line.strip().lstrip("-*•").strip().strip('"').strip("'").strip()
        if line:
            # Cut at first sentence terminator to keep it short.
            for term in (".", "!", "?"):
                if term in line:
                    line = line.split(term)[0] + term
                    break
            return line
    return "This activation is related to unspecified content."


# --------------------------------------------------------------------------- #
# Public API                                                                   #
# --------------------------------------------------------------------------- #
@dataclass
class LLMClusterInfo:
    cluster_id: int
    size: int
    representative_texts: list[str]
    explanation: str


def verbalize_clusters_with_llm(
    loaded: LoadedModel,
    activations: np.ndarray,
    texts: list[str],
    cluster_labels: np.ndarray,
    centroids: np.ndarray,
    top_k_examples: int,
    max_new_tokens: int = 60,
    progress: bool = True,
) -> tuple[list[LLMClusterInfo], dict[int, str]]:
    """Generate one natural-language explanation per cluster using `loaded.model`.

    Returns
    -------
    cluster_infos : list[LLMClusterInfo] ordered by cluster id
    explanation_by_cluster : {cluster_id: explanation string}
    """
    num_clusters = centroids.shape[0]
    infos: list[LLMClusterInfo] = []
    explanation_by_cluster: dict[int, str] = {}

    iterator = range(num_clusters)
    if progress:
        iterator = tqdm(iterator, desc="LLM verbalize")

    for c in iterator:
        idxs = np.where(cluster_labels == c)[0]
        if len(idxs) == 0:
            explanation = "This activation is related to an empty cluster."
            infos.append(LLMClusterInfo(
                cluster_id=c, size=0, representative_texts=[], explanation=explanation,
            ))
            explanation_by_cluster[c] = explanation
            continue
        d = np.linalg.norm(activations[idxs] - centroids[c], axis=1)
        order = np.argsort(d)[: min(top_k_examples, len(idxs))]
        rep_idxs = idxs[order].tolist()
        rep_texts = [texts[i] for i in rep_idxs]

        prompt = _build_prompt(loaded.tokenizer, rep_texts)
        explanation = _generate_one(loaded, prompt, max_new_tokens=max_new_tokens)
        # Light normalisation so downstream code stays clean.
        if not explanation.lower().startswith("this activation"):
            explanation = "This activation is related to " + explanation.rstrip(".") + "."

        infos.append(LLMClusterInfo(
            cluster_id=c,
            size=int(len(idxs)),
            representative_texts=rep_texts,
            explanation=explanation,
        ))
        explanation_by_cluster[c] = explanation

    return infos, explanation_by_cluster


def verbalize_per_sample_with_llm(
    loaded: LoadedModel,
    activations: np.ndarray,
    texts: list[str],
    top_k_neighbours: int,
    max_new_tokens: int = 60,
    cache_by: Callable[[int], int] | None = None,
    progress: bool = True,
) -> list[str]:
    """Per-sample neighbourhood-conditioned verbalization (no clustering required).

    For each sample i, find the top_k_neighbours nearest texts in activation
    space (excluding i itself) and prompt the LM to describe what they share.
    `cache_by(i)` returns a hashable key; samples that share a key reuse the
    same generation. By default each sample gets its own call (slow).
    """
    n = activations.shape[0]
    # Pairwise distances on the fly (avoid building the full NxN matrix).
    cache: dict[int, str] = {}
    explanations: list[str] = []

    # Pre-normalize for fast cosine-style ranking; the absolute scale matters
    # less than the relative neighbour order so L2 is fine.
    iterator = range(n)
    if progress:
        iterator = tqdm(iterator, desc="LLM verbalize/sample")

    for i in iterator:
        key = cache_by(i) if cache_by is not None else i
        if key in cache:
            explanations.append(cache[key])
            continue
        d = np.linalg.norm(activations - activations[i], axis=1)
        d[i] = np.inf
        nb = np.argpartition(d, top_k_neighbours)[:top_k_neighbours]
        rep_texts = [texts[j] for j in nb]
        prompt = _build_prompt(loaded.tokenizer, rep_texts)
        explanation = _generate_one(loaded, prompt, max_new_tokens=max_new_tokens)
        if not explanation.lower().startswith("this activation"):
            explanation = "This activation is related to " + explanation.rstrip(".") + "."
        cache[key] = explanation
        explanations.append(explanation)

    return explanations
